### ISSUE TITLE
Set Up Project Structure and Dependencies

### ISSUE THREAD

**Issue by minhe7735** [052223-java-angular/viet-min-p0#6]
Description: Set up the initial project structure, add necessary dependencies, and ensure that the project can be built and run successfully.

SP: 1

Acceptance Criteria: The project is properly structured, necessary dependencies are added, and the project builds and runs successfully.

**Comment by vtran91** [comment]
Created classes for tables

**Comment by vtran91** [comment]
Not too sure about structured properly, but folders made, dependencies added to Pom
